application: government-services
version: 2-i-0
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /api/.*
  script: main.api

- url: /.*
  script: main.application
  login: admin

libraries:
- name: jinja2
  version: latest
