application: government-services
version: 1-3-1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /views
  static_dir: views

- url: /.*
  script: main.application
  login: admin

libraries:
- name: jinja2
  version: latest
